### ISSUE TITLE
The spike count output could overflow.

### ISSUE THREAD

**Issue by gogoalexy** [twetto/iq-neuron#1]
Given the network configuration in [repo](https://github.com/gogoalexy/VisionBot/tree/master/eval/iq-neuron/inputs), if you access the spike count after the first step of simulation, you will get the following results:
`0, -1, 0, 0, 0, 1255790405, 120, 1447830186`
The numbers are too large to be true and the "-1" also indicates that overflow occurs.

**Comment by twetto** [comment]
It seemed like I didn't initialize `_spike_count` at first. Plz check again.
